services:
  redpanda:
    container_name: redpanda
    image: docker.arvancloud.ir/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - services
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:9644/v1/status/ready" ]
      start_period: 5s
      interval: 3s

  console:
    container_name: redpanda-console
    image: docker.arvancloud.ir/redpandadata/console:latest
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    networks:
      - services
    ports:
      - 9100:8080
    depends_on:
      - redpanda

  clickhouse:
    image: docker.arvancloud.ir/clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:            # important for high-load setups
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8123/ping | grep -q 'Ok.'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - services

networks: 
  services:
    name: ${APP_NAME:-sepahram}_network

volumes:
  clickhouse_data:
  clickhouse_logs:

    